# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  apt_packages:
    - graphviz  # used for "dot" graphs
sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true
# the requirements.txt override some RTD defaults.
# ideally it has to be updated from time to time
# with latest libraries versions.
python:
   install:
   - requirements: docs/requirements.txt
